### ISSUE TITLE
Question about cross-view node pairs code?

### ISSUE THREAD

**Issue by hantengyue** [sezinata/MANE#1]
Where is the code for constructing cross-view intra node pairs and constructing cross-view cross node pairs code???

**Comment by sezinata** [comment]
They are referred to as cost2 and cost3, respectively. You can also have a look at  commented "clear version of cost1 cost2 and cost3". They are all located in "main...py" files which include class itself as well.

**Comment by Dangwei-dw** [comment]
Hi, Can you provide the code for data preprocessing?
